# Generated by Django 5.0.2 on 2024-02-28 13:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('date', models.DateField()),
                ('created_at', models.DateField(default=datetime.datetime(2024, 2, 28, 13, 28, 33, 739850))),
            ],
        ),
    ]
