# Generated by Django 5.0.2 on 2024-02-28 13:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0003_alter_appointment_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2024, 2, 28, 13, 43, 20, 143218)),
        ),
    ]
