# Generated by Django 5.0.2 on 2024-02-28 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('speciality', models.CharField(choices=[('Allgemeinmedizin', 'Allgemeinmedizin'), ('Radiologe', 'Radiologe'), ('Hautarzt', 'Hautarzt')], max_length=30)),
                ('title', models.CharField(choices=[('Dr.', 'Dr.'), ('Prof. Dr.', 'Prof. Dr.'), ('Dr. rer. nat.', 'Dr. rer. nat.')], max_length=30)),
            ],
        ),
    ]
